name: pull_request

on:
  pull_request:
    branches:
      - main
jobs:

  unit-testing-and-build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v
    - uses: actions/setup-python@v4
    - uses: pre-commit/action@v3.0.0
